### ISSUE TITLE
Provide option similar to curl's `--connect-to`

### ISSUE THREAD

**Issue by fasterthanlime** [hatoo/oha#115]
This is probably a rare use case (but it's ours!).

`curl` provides a `connect-to` option to override DNS resolution and always connect directly to an IP address for a given hostname+port.

Since `oha` uses hyper, and `hyper` allows passing a `Resolver`, it seems this would be reasonably easy to implement. I can try and give it a shot if you'd accept a PR for that in oha.

Let me know what you think!

**Comment by hatoo** [comment]
Looks good.

Yes, the implementation would be relativly easy because `oha` resolves address manually by using `trust_dns_resolver` since `oha` uses `hyper`'s low-level API for performance.

I'm looking forward to your PR!
