### ISSUE TITLE
Bad numbers?

### ISSUE THREAD

**Issue by xHyroM** [hatoo/oha#176]
oha: `oha-linux-amd64 -j -z 10s -m GET http://localhost:3000`
![image](https://user-images.githubusercontent.com/56601352/183265932-7aa063af-6fee-4ecb-9a6c-06fc37c463cb.png)
why average, slowest, fastest is very small?

bombardier: `bombardier -p r -o j -l -c 40 -d 10s -m GET http://localhost:3000`
![image](https://user-images.githubusercontent.com/56601352/183266033-c8fbcf4e-0325-4070-a7cc-48a0fcfea9f7.png)

Could you implement properties min, max, average r/s ? Also pXX r/s

**Comment by hatoo** [comment]
`oha` prints a second and [bombardier](https://github.com/codesenberg/bombardier/blob/7871b16dc77ec3121d7ceb9ef47d42416a8bf9f1/internal/test_info.go#L112) prints a microsecond.
If the value of `oha` multiplies 1e6, then there is no big difference.
I think printing a second (not a microsecond) is a decent choice.

> Could you implement properties min, max, average r/s ? Also pXX r/s

Seems good, I'll create an issue for it
