### ISSUE TITLE
Are there some differences between 'Response time' and 'Latency' in the report?

### ISSUE THREAD

**Issue by Hexilee** [hatoo/oha#189]
![report](https://user-images.githubusercontent.com/25378640/190362929-8337e83b-4cca-44c8-a419-1f474ef37d1d.png)

**Comment by hatoo** [comment]
Could you tell me about a strange point in your image?
It looks good to me.

**Comment by Hexilee** [comment]
Yes, it looks good. But I'm a little confused about the `Response time` in `Response time histogram` and the `Latency` in `Latency distribution`, do they have the exact the same definition? Could we call them ``Latency histogram` or `Response time distribution`?

**Comment by hatoo** [comment]
Oh, I see.

> the Response time in Response time histogram and the Latency in Latency distribution, do they have exactly the same definition?

Yes they have exactly the same definition and are generated from the [exact same data](https://github.com/hatoo/oha/blob/master/src/printer.rs#L361-L364).

> Could we call them Latency histogram or Response time distribution?

The output is simply copied from [hey](https://github.com/rakyll/hey).
But `oha` doesn't aim to the exact clone of `hey`.
I think it's good to use the same term for both.
I prefer to use `Response time`.
Thanks.

**Comment by Hexilee** [comment]
Well, thanks.
