### ISSUE TITLE
Option to count only successful requests in response time statistics

### ISSUE THREAD

**Issue by Vanav** [hatoo/oha#212]
I have load test, that fast fails some requests, it is a rate limiting and is expected. I'd like to know the real response time of 2xx responses, without fast error page. Example:
```
./oha -H "accept-language: ru" -c 50 -t 5s -z 30s -q 20 --disable-keepalive https://example.com
Summary:
  Success rate: 1.0000
  Total:        30.0009 secs
  Slowest:      3.9235 secs
  Fastest:      0.1350 secs
  Average:      0.8213 secs
  Requests/sec: 20.0327

  Total data:   8.20 MiB
  Size/request: 13.97 KiB
  Size/sec:     279.96 KiB

Response time histogram:
  0.135 [1]   |
  0.514 [440] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.893 [0]   |
  1.272 [2]   |
  1.650 [3]   |
  2.029 [10]  |
  2.408 [46]  |■■■
  2.787 [42]  |■■■
  3.166 [25]  |■
  3.545 [26]  |■
  3.923 [6]   |

Latency distribution:
  10% in 0.1545 secs
  25% in 0.1632 secs
  50% in 0.1735 secs
  75% in 1.8177 secs
  90% in 2.7663 secs
  95% in 3.1871 secs
  99% in 3.5202 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.1125 secs, 0.0893 secs, 0.1767 secs
  DNS-lookup:   0.0003 secs, 0.0000 secs, 0.0846 secs

Status code distribution:
  [429] 441 responses
  [200] 160 responses
```
You can see that e.g. median latency (`50% in 0.1735 secs`) is not very useful in this test, because it includes both successful responses (2xx) and fast error pages (not 2xx).

But in other tests it may be useful to count errors to, e.g. for 502 error on backend timeout (60s), so I think it should be an option.

**Comment by wjhoward** [comment]
I could take a look at this if you would like @hatoo ?

**Comment by hatoo** [comment]
@wjhoward 
Thanks ❤️ , I would like it.

My rough thought is that when `oha` receives some flag for it, `Response time histogram:` and `Latency distribution:` will be printed for each both succeeded and unseeded logs. It should be done for both default print and `JSON` output.

 But if you find more better or simpler implementation, don't hesitate to do that.

**Comment by wjhoward** [comment]
@hatoo That makes sense, I will have a look and let you know how I get on!

**Comment by hatoo** [comment]
#296
