### ISSUE TITLE
HTTP/2 seems not to work

### ISSUE THREAD

**Issue by tnmtechnologies** [hatoo/oha#224]
I have set  the --http-version 2 in the command (url is http).
oha sends a HTTP/1.1 request .

My service supports HTTP/2 (checked with a curl HTTP/2 request). 

oha 0.5.8

OS
Edition	Windows 10 Enterprise
Version	22H2

**Comment by hatoo** [comment]
Thanks for the issue.
Yes, even though `--http-version` exists, HTTP/2 isn't supported.
To support HTTP/2, we need to handle that HTTP/2 can send multiple requests in one connection while HTTP/1 doesn't.
I'm planning to add HTTP/2 support when [hyper](https://github.com/hyperium/hyper) release 1.x version.

**Comment by hatoo** [comment]
HTTP/2 support #326 has merged!
