### ISSUE TITLE
oha failure with --http-version 3

### ISSUE THREAD

**Issue by tnmtechnologies** [hatoo/oha#225]
When I set --http-version 3 in the oha command, oha fails with this message:

`panicked at 'unexpected request version: HTTP/3.0', ....\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.14.25\src\proto\h1\role.rs:1135:22
`

oha 0.5.8

OS
Edition	Windows 10 Enterprise
Version	22H2

**Comment by hatoo** [comment]
HTTP/3 can't be supported before https://github.com/hyperium/hyper/issues/1818 so it's better to put a more proper message.
I'll fix it.
