### ISSUE TITLE
Profile-Guided Optimization (PGO) improvements

### ISSUE THREAD

**Issue by zamazan4ik** [hatoo/oha#264]
Recently I evaluated Profile-Guided Optimization (PGO) improvements on different software (the results are [here](https://github.com/zamazan4ik/awesome-pgo/)).

Regarding Oha the most interesting examples are PGO results on [Drill](https://github.com/fcsonline/drill/issues/185) and [Goose](https://www.tag1consulting.com/blog/golden-goose-egg-compile-time-adventure). I think Oha performance can be improved by PGO as well.

**Comment by hatoo** [comment]
@zamazan4ik 

Thanks for your issue!

I'm trying PGO in #268.
Since I've never considered PGO before, I would very much appreciate if you give me some advice.

**Comment by zamazan4ik** [comment]
I can suggest you read my materials about PGO [here](https://github.com/zamazan4ik/awesome-pgo/). For the Rust projects, starting with [cargo-pgo](https://github.com/Kobzol/cargo-pgo) will be a good option.
