### ISSUE TITLE
It does not work on Windows 10

### ISSUE THREAD

**Issue by alikhaleghi94** [hatoo/oha#273]
Hello, thank you for your great project.

I downloaded the Windows 10 version and entered this command in the Windows file explorer, both with cmd and with powershell.

.\oha-windows-amd64.exe oha -c 10 -t 5s -z 30s -q 10 --disable-keepalive https://en.wikipedia.org

But every time with this message👇

error: unexpected argument 'https://en.wikipedia.org' found
Usage: oha [FLAGS] [OPTIONS] <url>
For more information, try '--help'.

thanks⭐

**Comment by hatoo** [comment]
could you check

```
.\oha-windows-amd64.exe -c 10 -t 5s -z 30s -q 10 --disable-keepalive https://en.wikipedia.org/
```

runs?

**Comment by alikhaleghi94** [comment]
Oh its work !Thanks a lot

**Comment by hatoo** [comment]
Great. I'll close this issue.
