### ISSUE TITLE
incorrect header host value?

### ISSUE THREAD

**Issue by exoticknight** [hatoo/oha#308]
I tried using it like below, hoping to simulate the access to a service on my local machine. The service online is a service of xxx.com, so use the host header to simulate it.

```bash
oha -H "host:xxx.com" -z 30m "http://127.0.0.1:8000"
```

What is received on the server side is

```
Request {
  bodyUsed: false,
  headers: Headers {
  accept: "*/*",
  "accept-encoding": "gzip, compress, deflate, br",
  host: "127.0.0.1:8000, xxx.com",
  "user-agent": "oha/0.6.3"
},
  method: "GET",
  redirect: undefined,
  url: "http://127.0.0.1:8000/"
}
```

It does not meet my expectations. The value of host should be `xxx.com` instead of `127.0.0.1:8000, xxx.com`

**Comment by hatoo** [comment]
Thanks for reporting!

You can override Host header by using `--host` option but `-H`  append a value instead of overriding.
I fixed it #309.

Feel free to reopen this issue if you think the issue remains.
