### ISSUE TITLE
(Question) How can I pass a JSON body?

### ISSUE THREAD

**Issue by ViniciusLucchesi** [hatoo/oha#314]
I developed an Actix-web API, and the route that I want to test requires a JSON body like this: 

```JSON
{
  "code": "7843.92.73"
}
```

I tried the following URL based on @hatoo's response to [kenessajr's issue](https://github.com/hatoo/oha/issues/146), but it didn't work.

```bash
oha -T application/json -d 'code=7843.92.73' 'http://127.0.0.1:7000/code/view'
```

The response from `oha` was `Status code distribution: [400] 200 responses`, which is the same status code response I get when I use `Thunder Client` and don`t pass the JSON body.

Does anyone know what I am doing wrong?

**Comment by hatoo** [comment]
You should try just putting a JSON to `-d` option

Such like
```
oha -n 1 -T application/json -d '{"code": "7843.92.73"}' http://localhost:8888
```


```
$ nc -l -p 8888
GET / HTTP/1.1
accept: */*
accept-encoding: gzip, compress, deflate, br
host: localhost:8888
user-agent: oha/0.6.3
content-type: application/json
content-length: 22

{"code": "7843.92.73"}
```

I think this request is what you want.

**Comment by ViniciusLucchesi** [comment]
Thanks @hatoo, it works
