### ISSUE TITLE
Timed out requests not reported at all in stats

### ISSUE THREAD

**Issue by huntharo** [hatoo/oha#387]
## Motivations
- When `oha` exits due to the `-z 10s` parameter, any in-flight requests are simply aborted
- Aborted requests are not reported at all
- Normally this would not be an issue
- However, when testing for requests that might hang 8 seconds and with high connection counts (which causes 5 second delays for some connection), several of the requests that are aborted actually started 8-13 seconds earlier for a service with a nominal response time of 50 ms
- It would be nice to have an indication of the duration of the requests that were aborted so it does not appear that all was well when the test ended

## Proposal
- Report these as 499s
  - `nginx` and others use 499 to indicate that the client aborted the connection
  - Report the time as the time taken up to that point
    - This may count some as very short (e.g. 1 ms) and others as very long if they were hung (e.g. 13 seconds)
  - I'm torn on this... it will cause some wiggle in the stats that could be disruptive
- Do not abort the requests immediately
  - Stop issuing new requests
  - Wait for the inflight requests to finish and collect their status code and real response times
  - Set a timeout (e.g. 10 seconds) and indicate to the user that the app is waiting for in-flight requests to finish
  - At the end of the timeout, perform the current request abort if any requests have not yet returned and report these as 499s with their durations as the duration when they were aborted
  - While I do not love that the app will not stop at exactly 10 seconds, I think this is the best solution to avoid masking the existence of problems - This does avoid pulling the average response times way down from requests that were aborted 1 ms after being sent, which is good, but if the nominal response time is 100 seconds then it would still pull that average down from aborts at 10 seconds

**Comment by hatoo** [comment]
@huntharo 
I think this is fixed at #392 
Now when `-z` option is set, `oha` aborts requests when the deadline has arrived (as same as before) because we must respect a user-specified deadline. But it reports the number of aborted requests.

If anyone cares about aborting requests, we can run without `-z` option which doesn't abort request from `oha`.

**Comment by huntharo** [comment]
> @huntharo 
> 
> I think this is fixed at #392 
> 
> Now when `-z` option is set, `oha` aborts requests when the deadline has arrived (as same as before) because we must respect a user-specified deadline. But it reports the number of aborted requests.
> 
> 
> 
> If anyone cares about aborting requests, we can run without `-z` option which doesn't abort request from `oha`.


This actually sounds great. Just an alert that things were canceled should clue people in that they might have hung it long duration requests. Thanks!
