### ISSUE TITLE
Make relevant options mutually exclusive

### ISSUE THREAD

**Issue by jalil-salame** [hatoo/oha#417]
Currently `--unix-socket PATH` causes the `URL` to be ignored, since I added VSOCK support `--vsock-addr CID:PORT` also ignores the `URL`.

One option would be to use `unix:///path/to/socket` as the URL for unix sockets, but `vsock://CID:PORT` is not ideal for VSOCK (there is no precedent and url parses the CID as a Domain).

The other option I see (which I prefer). Is to try using clap groups to specify that either `--unix-socket PATH`, `--vsock-addr CID:PORT` or `URL` must be provided, and have clap display an error otherwise.

This is strictly QOL, but I think it would be worth it. If you are interested I can give it a shot c:

**Comment by hatoo** [comment]
Thank you for your proposal.

> The other option I see (which I prefer). Is to try using clap groups to specify that either --unix-socket PATH, --vsock-addr CID:PORT or URL must be provided, and have clap display an error otherwise.

I like this option, but `URL` should always be provided because `oha` needs to know the URL path, and setting host header is good.

Please make `--unix-socket` or `--vsock-addr` mutually exclusive.

> This is strictly QOL, but I think it would be worth it. If you are interested I can give it a shot c:

Thanks! I'm looking forward to it.
