### ISSUE TITLE
OHA sometimes causes the Macbook M2 to freeze and reboot.

### ISSUE THREAD

**Issue by devcaeg** [hatoo/oha#428]
### Describe the bug

I am using OHA every day, but I have a problem and that is that sometimes when I run the command ```oha -c 500 -z 10s http://localhost:3000/``` nothing appears in the console and the laptop freezes after a few seconds and restarts automatically.

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M2
    Memory: 571.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    bun: 1.0.30 - /opt/homebrew/bin/bun
```

**Comment by hatoo** [comment]
It looks like #384 
Is it happening on the latest release?

**Comment by devcaeg** [comment]
In version 1.4.0 it hasn't happened to me yet, but I would like to wait a few more days of use to confirm, since the error happens randomly.

**Comment by devcaeg** [comment]
Since version 1.4.0, the error has not reoccurred.
