### ISSUE TITLE
About version scheme

### ISSUE THREAD

**Issue by chenrui333** [hatoo/oha#430]
👋 looks like there is a new version of 1.4.0-pgo, but the `--version` output is still `1.4.0`, maybe it is better to just create a new patch version as `1.4.1` (which also matches with SemVer scheme). Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/166328

**Comment by hatoo** [comment]
Thanks,

I've published a `1.4.0-pgo` tag because I've just updated a CI that doesn't contain app code changes.
It feels odd to me to publish 1.4.1 with such a situation... But sure, I'll publish 1.4.1. Please wait a few minutes.

**Comment by chenrui333** [comment]
it is fine, the better versioning scheme is more easier for downstream consumption.

Thanks for pushing a new release.

**Comment by chenrui333** [comment]
FYI, your crate did not get updated, https://crates.io/crates/oha

**Comment by chenrui333** [comment]
The new release works for me, closing the issue now. Thanks again!
