### ISSUE TITLE
Add HTTP pipelining support

### ISSUE THREAD

**Issue by sdeleuze** [hatoo/oha#438]
Like what `wrk` allows with https://github.com/wg/wrk/blob/master/scripts/pipeline.lua, it would be nice to be able to use HTTP pipelining with `oha` (maybe combined with the dynamic url feature, not sure).

This is the only feature that is missing for my use case, thanks for building such great tool!

**Comment by hatoo** [comment]
HTTP pipelining won't be supported. 🙇 
Because our backend, [hyper](https://github.com/hyperium/hyper) doesn't support it https://github.com/hyperium/hyper/issues/2596

You can use HTTP2 and it has similar features.
