### ISSUE TITLE
Failed to install using cargo on windows

### ISSUE THREAD

**Issue by JQiue** [hatoo/oha#460]
```
   Compiling http-body-util v0.1.1
   Compiling humantime v2.1.0
   Compiling strum v0.26.2
   Compiling ratatui v0.26.1
   Compiling clap v4.5.4
   Compiling futures-executor v0.3.30
   Compiling rand_regex v0.17.0
   Compiling futures v0.3.30
   Compiling aws-lc-sys v0.14.1
error: failed to run custom build command for `aws-lc-sys v0.14.1`

Caused by:
  process didn't exit successfully: `C:\Users\ush2a\AppData\Local\Temp\cargo-installH17IT7\release\build\aws-lc-sys-0d38acf102f0cbd1\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=AWS_LC_SYS_INTERNAL_NO_PREFIX
  cargo:rerun-if-env-changed=AWS_LC_RUST_INTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC

  --- stderr
  Missing dependency: cmake
  thread 'main' panicked at C:\Users\ush2a\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\aws-lc-sys-0.14.1\builder/main.rs:332:34:
  called `Result::unwrap()` on an `Err` value: "Required build dependency is missing. Halting build."
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `oha v1.4.3`, intermediate artifacts can be found at `C:\Users\ush2a\AppData\Local\Temp\cargo-installH17IT7`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by sysmat** [comment]
- what was a solution?
- I have CI docker build with the same error
```docker
FROM rust:latest
RUN cargo install oha
```

```
error: failed to run custom build command for `aws-lc-sys v0.14.1`
Caused by:
  process didn't exit successfully: `/tmp/cargo-installS5GN3Q/release/build/aws-lc-sys-e92783bb8a8865a8/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=AWS_LC_SYS_INTERNAL_NO_PREFIX
  cargo:rerun-if-env-changed=AWS_LC_RUST_INTERNAL_BINDGEN
  cargo:rustc-cfg=x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
  --- stderr
  Missing dependency: cmake
  thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.14.1/builder/main.rs:
```

- RUST_BACKTRACE=full

```
Missing dependency: cmake
  thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.14.1/builder/main.rs:332:34:
  called `Result::unwrap()` on an `Err` value: "Required build dependency is missing. Halting build."
  stack backtrace:
     0:     0x55dee51ead06 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
     1:     0x55dee5211010 - core::fmt::write::he40921d4802ce2ac
     2:     0x55dee51e80df - std::io::Write::write_fmt::h5de5a4e7037c9b20
     3:     0x55dee51eaae4 - std::sys_common::backtrace::print::h11c067a88e3bdb22
     4:     0x55dee51ec257 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
     5:     0x55dee51ebfb9 - std::panicking::default_hook::h1633e272b4150cf3
     6:     0x55dee51ec6e8 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
     7:     0x55dee51ec5c2 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
     8:     0x55dee51eb206 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
     9:     0x55dee51ec314 - rust_begin_unwind
    10:     0x55dee514c9b5 - core::panicking::panic_fmt::ha6effc2775a0749c
    11:     0x55dee514ce23 - core::result::unwrap_failed::ha188096f98826595
    12:     0x55dee5159c89 - build_script_main::main::h62cab2359b04b87d
    13:     0x55dee514e363 - core::ops::function::FnOnce::call_once::ha701d3bf915b4149
    14:     0x55dee514db66 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc795fd9f6f8a5[347](https://git.arnes.si/docker/oha/-/jobs/861976#L347)
    15:     0x55dee514dc79 - std::rt::lang_start::{{closure}}::hffa10b83fd070ad6
    16:     0x55dee51e3871 - std::rt::lang_start_internal::h4d236095b69a230b
    17:     0x55dee514dc57 - std::rt::lang_start::h5fb0582405387a2a
    18:     0x55dee515b215 - main
    19:     0x7fa3fffd424a - <unknown>
    20:     0x7fa3fffd4305 - __libc_start_main
    21:     0x55dee514d121 - _start
    22:                0x0 - <unknown>
```

**Comment by JQiue** [comment]
> - what was a solution?
> - I have CI docker build with the same error
> ```docker
> FROM rust:latest
> RUN cargo install oha
> ```
> 
> ```
> error: failed to run custom build command for `aws-lc-sys v0.14.1`
> Caused by:
>   process didn't exit successfully: `/tmp/cargo-installS5GN3Q/release/build/aws-lc-sys-e92783bb8a8865a8/build-script-main` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-env-changed=AWS_LC_SYS_INTERNAL_NO_PREFIX
>   cargo:rerun-if-env-changed=AWS_LC_RUST_INTERNAL_BINDGEN
>   cargo:rustc-cfg=x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
>   --- stderr
>   Missing dependency: cmake
>   thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.14.1/builder/main.rs:
> ```
> 
> - RUST_BACKTRACE=full
> 
> ```
> Missing dependency: cmake
>   thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.14.1/builder/main.rs:332:34:
>   called `Result::unwrap()` on an `Err` value: "Required build dependency is missing. Halting build."
>   stack backtrace:
>      0:     0x55dee51ead06 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
>      1:     0x55dee5211010 - core::fmt::write::he40921d4802ce2ac
>      2:     0x55dee51e80df - std::io::Write::write_fmt::h5de5a4e7037c9b20
>      3:     0x55dee51eaae4 - std::sys_common::backtrace::print::h11c067a88e3bdb22
>      4:     0x55dee51ec257 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
>      5:     0x55dee51ebfb9 - std::panicking::default_hook::h1633e272b4150cf3
>      6:     0x55dee51ec6e8 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
>      7:     0x55dee51ec5c2 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
>      8:     0x55dee51eb206 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
>      9:     0x55dee51ec314 - rust_begin_unwind
>     10:     0x55dee514c9b5 - core::panicking::panic_fmt::ha6effc2775a0749c
>     11:     0x55dee514ce23 - core::result::unwrap_failed::ha188096f98826595
>     12:     0x55dee5159c89 - build_script_main::main::h62cab2359b04b87d
>     13:     0x55dee514e363 - core::ops::function::FnOnce::call_once::ha701d3bf915b4149
>     14:     0x55dee514db66 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc795fd9f6f8a5[347](https://git.arnes.si/docker/oha/-/jobs/861976#L347)
>     15:     0x55dee514dc79 - std::rt::lang_start::{{closure}}::hffa10b83fd070ad6
>     16:     0x55dee51e3871 - std::rt::lang_start_internal::h4d236095b69a230b
>     17:     0x55dee514dc57 - std::rt::lang_start::h5fb0582405387a2a
>     18:     0x55dee515b215 - main
>     19:     0x7fa3fffd424a - <unknown>
>     20:     0x7fa3fffd4305 - __libc_start_main
>     21:     0x55dee514d121 - _start
>     22:                0x0 - <unknown>
> ```

As the error says, you lack cmake
