### ISSUE TITLE
oha Potential Memory Leak

### ISSUE THREAD

**Issue by nanqic** [hatoo/oha#475]
Description:
While running 'oha' continuously, it has been observed that the memory usage keeps increasing over time. Initially, it starts at 2%, but after 6 hours it rises to 16%, and after a day it reaches 50%.

Command executed:
`nohup oha -c 500 'http://10.0.10.11/' -z 99h -m HEAD -t 30s --no-tui >>.logs/oha.log &`

thanks.

**Comment by hatoo** [comment]
Currently, `oha` is collecting *ALL* data of each request.
So memory usage increases proportionally to the number of requests.

It is potentially solved by using a smarter algorithm such as `hdrhistogram`. But not yet implemented.

#364

**Comment by nanqic** [comment]
It will be helpful, thanks for this project!
