### ISSUE TITLE
Packaged for Arch Linux

### ISSUE THREAD

**Issue by svenstaro** [hatoo/oha#57]
Hey, not really an issue but I think this is a cool tool and I packaged it for Arch Linux [here](https://aur.archlinux.org/packages/oha/). Once you make a release including the LICENSE file, I'll add that as well. If it's popular it has a good chance to become part of the [community] repository.

**Comment by svenstaro** [comment]
Of course, feel free to close this once you've taken note. :)

Some projects like to add information like this to the README to inform users how to install their tools.

**Comment by hatoo** [comment]
Awesome!

Since I don't know how to install this via Arch Linux package.
Could you provide a command to install this in Arch Linux?
I'll add it to README.

**Comment by svenstaro** [comment]
I did a quick PR for this. Feel free to format it as you see fit. :)

**Comment by hatoo** [comment]
Thank you.
