### ISSUE TITLE
Feature request: advised to add the result display for testers to check whether the command is correct

### ISSUE THREAD

**Issue by dakaka001** [hatoo/oha#599]
advised to add the result display for testers to check whether the command is correct
like this:
oha.exe -n 1 -c 1 --result -m POST -H "Authorization: eyJhbGciOiJSUzI1NiJ9" -T application/json;charset=utf-8 -d {"groupId":7,"name":"","userId":110,"roleId":130}    http://xxx/api/userAppList 

{"code":0,"msg":"Success","data":[]}

**Comment by hatoo** [comment]
Great idea, thank you.
