### ISSUE TITLE
Adding a new installation method to the README

### ISSUE THREAD

**Issue by curry798** [hatoo/oha#601]
Hi, we have implemented a lightweight [package manager using shell and awk](https://www.x-cmd.com/pkg/).
It helps you download oha release packages from the internet and extract them into a unified directory for management, without requiring root permissions.

I mean, can the installation method provided by x-cmd be added to the oha README?
[The installation method for the x command](https://www.x-cmd.com/start/)

install oha:
```bash
x env use oha
```
[oha demo](https://www.x-cmd.com/pkg/oha): x-cmd recorded a demo and article for oha

I apologize in advance if it's not appropriate to raise this topic using a GitHub issue.
Looking forward to your reply :) !

**Comment by hatoo** [comment]
Looks good!

Could you make PR?

**Comment by curry798** [comment]
> Looks good!
> 
> Could you make PR?

yes ! https://github.com/hatoo/oha/issues/601
