### ISSUE TITLE
Running with -q hangs

### ISSUE THREAD

**Issue by black-snow** [hatoo/oha#603]
When I run `oha` with `-q` (and `-w`?) is just hangs at some point. It doesn't drain any CPU than and seems just dead-locked.

Example: `oha -q 5 -z 30s -m POST -t 30s -d "$body" -T 'application/json' -w 'http://localhost:8000/score'`

Sometimes it hangs after 4 seconds, somtimes after 22.

**Comment by devnev** [comment]
Same for me, with `oha -z 10s -q 30 -t 5s <url>`, both with and without `--no-tui`, it hangs after a few seconds, and I have to `pkill oha` from a different terminal

**Comment by hatoo** [comment]
Thank you for your reports.

Could you tell me a OS and oha's version?

**Comment by devnev** [comment]
oha 1.4.7, installed with brew, MacOS Sonoma 14.5, Intel x64.

I'm actually finding that if I replace `-z 10s` with `-n 300` it works. There's some weirdness but I'm not sure if that is from oha or the service I'm testing.

**Comment by black-snow** [comment]
oha 1.4.7

macOS (14 and 15) as well as various Linuxes

**Comment by hatoo** [comment]
I can't reproduce it in both MacOS15 x64 and Ubuntu x64.

Could you tell me about the server side? If codes aren't available, please tell me the language and framework versions.

Is the `-t` option necessary to reproduce this issue?

**Comment by black-snow** [comment]
Sadly, I can't test right now. The server is a Python app (3.12, fastapi + uvicorn both latest).

**Comment by nekevss** [comment]
I'm having the same issue with oha version 1.4.7 on Pop!_OS 22.04 where it hangs when provided `-z 2m -q 1` (optionally with `-w`). I have found that adding `--latency-correction` does stop oha from hanging, but that's probably due to avoiding `client::work_until_with_qps`.

**Comment by black-snow** [comment]
Another exec that hangs: `oha -q 30 -z 10s -m POST -t 30s -w -d "$body" -T 'application/json' 'http://localhost:8000/get_score'`

Will try with `-n` instead of `-t`.

**Comment by hatoo** [comment]
I think it's fixed in #613 
Feel free to reopen this issue
Thank you!

**Comment by black-snow** [comment]
Nice! Looking forward to the next release then.
