### ISSUE TITLE
Use more colors

### ISSUE THREAD

**Issue by svenstaro** [hatoo/oha#64]
I think for very quickly looking at the output of your load test it would be cool if oha used some colors with sane defaults for how long something takes (maybe green 0s - 0.3s, orange, 0.3-0.8, red, >=0.8?).

I suggest using colors in the TUI view and in the final output. Of course, make it into an option but I think it should be "auto" by default so that if the terminal is detected to be capable of colors, it should output using colors.

**Comment by wjhoward** [comment]
@hatoo Do you want any more colors added before this issue is closed? Could maybe add some colors to other places, e.g. the latency distributions? If so I am happy to raise a PR for this.

**Comment by hatoo** [comment]
@wjhoward 
That looks good! PRs are welcome!
For compatibility, it must not use RGB color. It means you can't use Color::Rgb https://docs.rs/tui/0.19.0/tui/style/enum.Color.html
See #209

**Comment by wjhoward** [comment]
Sounds good, I've started work on a PR, primarily adding color / style to the printer view.

**Comment by hatoo** [comment]
Great. Please don't forget to respect `--disable-color` flag!

**Comment by hatoo** [comment]
#292

colors are almost everywhere now.
Feel free to reopen if you think there are not enough colors.
